version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install

  build:
    commands:
      - npm run build

artifacts:
  files:
    - "./dist/hoobank.svg"
    - "./dist/index.html"
    - "./dist/assets/"
    # Include all files and directories in the build artifacts.
  base-directory: "project_hoobank/"
  discard-paths: yes
cache:
  paths:
    - node_modules
    # Cache the node_modules directory to speed up future builds.
